version: '3'

volumes:
  pgdata:
  oracle:

services:
  oracle:
    image: doctorkirk/oracle-19c
    ports:
      - "1521:1521"
    environment:
      ORACLE_SID: DB
      ORACLE_PWD: qwertyK
    volumes:
      - oracle:/opt/oracle/oradata

  zookeeper:
    image: debezium/zookeeper:1.8
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: debezium/kafka:1.8
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=astreya
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${PWD}/db/init:/docker-entrypoint-initdb.d

  kafka-connect:
    image: romanyuknr/connect
    build:
      context: docker/connect
    volumes:
      - ./mount/connect/config:/kafka/config:rw
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - postgres
      - oracle
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  kafka-connect-ui:
    image: landoop/kafka-connect-ui:latest
    network_mode: bridge
    ports:
      - "8000:8000"
    depends_on:
      - kafka-connect
    environment:
      CONNECT_URL: http://kafka-connect:8083