--create table client (
--    id bigint primary key GENERATED ALWAYS AS IDENTITY,
--    login VARCHAR(255) NOT NULL UNIQUE,
--    password VARCHAR(255) NOT NULL
--);
--
--create table outbox (
--    id bigint primary key GENERATED ALWAYS AS IDENTITY,
--    aggregate_type VARCHAR(255) NOT NULL,
--    aggregate_id BIGINT NOT NULL,
--    type VARCHAR(255) NOT NULL,
--    payload JSONB NOT NULL
--);
--
--insert into client (login, password) values ('jamik', 'jamik');
--
--insert into outbox (aggregate_type, aggregate_id, type, payload)
--values ('client', 1, 'INSERT', '{"login" : "jamik", "password" : "jamik"}');
--
--create publication outbox_publication for table outbox;

create schema cashflow;

create user cashflow with password 'qwerty';
create user migration with password 'qwerty';

alter schema cashflow owner to cashflow;

grant usage on schema cashflow to migration;

set role cashflow;

create table all_data (
    id bigint primary key generated by default as identity,
    name varchar(256) not null,
    created date not null,
    modified timestamp not null,
    price numeric(4, 2) not null,
    comment text
);

create table dep_data (
    id bigint primary key generated by default as identity,
    all_data_id bigint not null,
    name varchar(256) not null,
    constraint for_key_all_data
     foreign key(all_data_id)
     references all_data(id)
);

--insert into all_data (name, created, modified, price, comment)
--values
--('lol', current_timestamp, current_timestamp, 10.22, 'adssdsadasdasdasdas');
--
--insert into dep_data (all_data_id, name)
--values
--(1, 'arrr');

set role 'user';

grant select, insert, update, delete, truncate on all tables in schema cashflow to migration;