create user cashflow identified by qwerty
    quota unlimited on USERS;
grant create session to cashflow;
grant create table to cashflow;
grant create sequence to cashflow;


CREATE TABLE cashflow.all_data(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(256) NOT NULL,
    created date not null,
    modified timestamp not null,ALTER USER migration quota unlimited on USERS;
    price number(4, 2) not null,
    comment clob not null,
    PRIMARY KEY(id)
);

create table cashflow.dep_data (
    id number generate by default as identity,
    all_data_id number not null,
    name varchar2(256),
    PRIMARY KEY(id),
    foreign key(all_data_id) references (cashflow.all_data.id)
);

insert into all_data (name, created, modified, price, comment)
values
('lol', current_timestamp, current_timestamp, 10.22, 'adssdsadasdasdasdas');

insert into dep_data (all_data_id, name)
values
(1, 'arrr');

create user migration identified by qwerty
    default tablespace logminer_tbs
    quota unlimited on logminer_tbs;

grant create session to migration;
grant create table to migration;
grant create sequence to migration;

GRANT SELECT ON V_$DATABASE to migration;
GRANT FLASHBACK ANY TABLE TO migration;
GRANT SELECT ANY TABLE TO migration;
GRANT SELECT_CATALOG_ROLE TO migration;
GRANT EXECUTE_CATALOG_ROLE TO migration;
GRANT SELECT ANY TRANSACTION TO migration;
GRANT LOGMINING TO migration;
GRANT LOCK ANY TABLE TO migration;
GRANT EXECUTE ON DBMS_LOGMNR TO migration;
GRANT EXECUTE ON DBMS_LOGMNR_D TO migration;
GRANT SELECT ON V_$LOG TO migration;
GRANT SELECT ON V_$LOG_HISTORY TO migration;
GRANT SELECT ON V_$LOGMNR_LOGS TO migration;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO migration;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO migration;
GRANT SELECT ON V_$LOGFILE TO migration;
GRANT SELECT ON V_$ARCHIVED_LOG TO migration;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO migration;
GRANT SELECT ON V_$TRANSACTION TO migration;


create table migration.signal (
    id varchar2(100) primary key,
    type varchar2(256) not null,
    data varchar2(1024) not null
);
